import type { NextPage } from 'next'
import Head from 'next/head'
import { Main } from '../styles/main.styled';
import {Container} from '../styles/containner.styled';
import { Grid } from '../styles/grid.styled';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>CSS-Grid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Container>
          <Grid col={12}>Header Section</Grid>
          <Grid col={4}>Left bar</Grid>
          <Grid col={6}>Content section</Grid>
          <Grid col={2}>Right section</Grid>
          <Grid col={12}>Footer section</Grid>
        </Container>
      </Main>

    </div>
  )
}

export default Home
